services:
  siwys-app:
    build:
      context: ./
      dockerfile: demo/app/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./demo/app:/demo/app
      - ./packages/react-js:/demo/app/node_modules/@yourself_id/react-js
      - app_node_modules:/demo/app/node_modules
    networks:
      - kc
  siwys-backend:
    build:
      context: ./
      dockerfile: demo/backend/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./demo/backend/src:/demo/backend/src
      - ./packages/api-js:/demo/backend/node_modules/@yourself_id/siwys-api-js
      - backend_node_modules:/demo/backend/node_modules
    networks:
      - kc
volumes:
  app_node_modules: {}
  backend_node_modules: {}
networks:
  kc:
    name: kc_default
    external: true
